<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="LAPTOP-IFFP6P5H" failures="5" tests="10" name="Test" time="28.738" errors="0" timestamp="2023-04-15T18:12:50 IST">
  <testcase classname="api.test.DD2Store" name="testCreateOrder" time="5.885"/>
  <testcase classname="api.test.DD2Store" name="testCreateOrder" time="1.771"/>
  <testcase classname="api.test.DD2Store" name="testCreateOrder" time="2.349"/>
  <testcase classname="api.test.DD2Store" name="testCreateOrder" time="2.04"/>
  <testcase classname="api.test.DD2Store" name="testCreateOrder" time="1.939"/>
  <testcase classname="api.test.DD2Store" name="deletePOwithOrderId" time="2.094">
    <failure type="java.lang.AssertionError" message="expected [200] but found [404]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [404]
at api.test.DD2Store.deletePOwithOrderId(DD2Store.java:37)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 34 stack frames]]>
    </failure>
  </testcase> <!-- deletePOwithOrderId -->
  <testcase classname="api.test.DD2Store" name="deletePOwithOrderId" time="2.128">
    <failure type="java.lang.AssertionError" message="expected [200] but found [404]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [404]
at api.test.DD2Store.deletePOwithOrderId(DD2Store.java:37)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 34 stack frames]]>
    </failure>
  </testcase> <!-- deletePOwithOrderId -->
  <testcase classname="api.test.DD2Store" name="deletePOwithOrderId" time="2.145">
    <failure type="java.lang.AssertionError" message="expected [200] but found [404]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [404]
at api.test.DD2Store.deletePOwithOrderId(DD2Store.java:37)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 34 stack frames]]>
    </failure>
  </testcase> <!-- deletePOwithOrderId -->
  <testcase classname="api.test.DD2Store" name="deletePOwithOrderId" time="1.834">
    <failure type="java.lang.AssertionError" message="expected [200] but found [404]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [404]
at api.test.DD2Store.deletePOwithOrderId(DD2Store.java:37)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 34 stack frames]]>
    </failure>
  </testcase> <!-- deletePOwithOrderId -->
  <testcase classname="api.test.DD2Store" name="deletePOwithOrderId" time="2.04">
    <failure type="java.lang.AssertionError" message="expected [200] but found [404]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [404]
at api.test.DD2Store.deletePOwithOrderId(DD2Store.java:37)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 34 stack frames]]>
    </failure>
  </testcase> <!-- deletePOwithOrderId -->
</testsuite> <!-- Test -->
